# My Finance Account Microservice - Database
version: '3.8'
name: my-finance-account-ms

services:
  finance-db:
    image: postgres:16-alpine
    container_name: finance-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d my_finance_account" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge